version: '3.1'

services:
  webapp:
    image: webapp
    build:
      context: .
      dockerfile: src/Webapp/Dockerfile
    secrets:
      - ConnectionStrings__DataConnectionString
    depends_on: 
      - orleanshost
  orleanshost:
    image: orleanshost
    build:
      context: .
      dockerfile: src/OrleansHost/Dockerfile
    secrets:
      - ConnectionStrings__DataConnectionString
      - ConnectionStrings__ReduxConnectionString

secrets:
  ConnectionStrings__DataConnectionString:
    file: ~/AppData/Roaming/Microsoft/UserSecrets/rrod-secrets/DataConnectionString.txt
  ConnectionStrings__ReduxConnectionString:
    file: ~/AppData/Roaming/Microsoft/UserSecrets/rrod-secrets/DataConnectionString.txt
