apiVersion: v1
kind: Service
metadata:
  name: rrod-service
spec:
  type: LoadBalancer
  selector:
    app: rrod
    role: web
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  externalIPs:
  - 192.168.0.116